export const galleryData = [
  { id: 1, src: "/assets/gallery/image1.jpg" },
  { id: 2, src: "/assets/gallery/image2.jpg" },
  { id: 3, src: "/assets/gallery/image3.jpg" },
  { id: 4, src: "/assets/gallery/image4.jpg" },
  { id: 5, src: "/assets/gallery/image5.jpg" },
  { id: 6, src: "/assets/gallery/image6.jpg" },
  { id: 7, src: "/assets/gallery/image7.jpg" },
  { id: 8, src: "/assets/gallery/image8.jpg" },
  { id: 9, src: "/assets/gallery/image9.jpg" },
  { id: 10, src: "/assets/gallery/image10.jpg" },
  { id: 11, src: "/assets/gallery/image11.jpg" },
  { id: 12, src: "/assets/gallery/image12.jpg" },
  { id: 13, src: "/assets/gallery/image13.jpg" },
  { id: 14, src: "/assets/gallery/image14.jpg" },
  { id: 15, src: "/assets/gallery/image15.jpg" },
  { id: 16, src: "/assets/gallery/image16.jpg" },
  { id: 17, src: "/assets/gallery/image17.jpg" },
  { id: 18, src: "/assets/gallery/image18.jpg" },
  { id: 19, src: "/assets/gallery/image19.jpg" },
  { id: 20, src: "/assets/gallery/image20.jpg" },
  { id: 21, src: "/assets/gallery/image21.jpg" },
];
